# -*- coding: utf-8 -*-
"""013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ii4no0DoZl_H8x8OhWK5HUP8MSo88Azx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from google.colab import files


uploaded = files.upload()

Base_Dados = pd.read_csv('unicorns till sep 2022.csv')


Base_Dados.shape

Base_Dados.head()

Base_Dados.columns

Base_Dados.info()

Base_Dados.isnull().sum()

plt.figure( figsize=(15,6) )
plt.title('Analisando Campos Nulos')
sns.heatmap( Base_Dados.isnull(), cbar=False );

Base_Dados.nunique()

Base_Dados['Industry'].unique()

Base_Dados['Industry'].value_counts( normalize=True )

plt.figure( figsize=(15,6) )
plt.title('Analise dos Setores')
plt.bar( Base_Dados['Industry'].value_counts().index, Base_Dados['Industry'].value_counts()  )
plt.xticks( rotation=45, ha='right' );

Analise = round( Base_Dados['Country'].value_counts( normalize=True ) * 100, 1 )

plt.figure( figsize=(15,6) )
plt.title('Analise dos Paises gerador de Unicornios')
plt.pie(
    Analise,
    labels = Analise.index,
    shadow=True,
    startangle=90,
    autopct='%1.1f%%'
);

plt.figure( figsize=(15,6) )
plt.title('Analise dos Paises gerador de Unicornios - Top 10')
plt.pie(
    Analise.head(10),
    labels = Analise.index[0:10],
    shadow=True,
    startangle=90,
    autopct='%1.1f%%'
);

Base_Dados['Date Joined'] = pd.to_datetime( Base_Dados['Date Joined'] )

Base_Dados['Date Joined'].head()

Base_Dados['Mes'] = pd.DatetimeIndex( Base_Dados['Date Joined'] ).month
Base_Dados['Ano'] = pd.DatetimeIndex( Base_Dados['Date Joined'] ).year

Base_Dados.head()